# Generated by Django 4.1.3 on 2022-11-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField()),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_location', models.CharField(max_length=50)),
                ('shop_owner', models.CharField(max_length=50)),
                ('shop_contacts', models.CharField(max_length=10)),
            ],
        ),
    ]
