# Generated by Django 4.1.3 on 2022-11-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('park_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='trails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('park_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='water',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('park_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='places',
        ),
    ]
