# Generated by Django 4.1.3 on 2022-11-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_parks_park_rename_trails_trail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='park_name',
            new_name='trail_name',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='park_name',
            new_name='water_name',
        ),
        migrations.AddField(
            model_name='park',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trail',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='water',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
